name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use the version of Node.js your project needs

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --coverage  # Generate coverage report

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Add your Codecov token in GitHub secrets
          files: ./coverage/*.json  # Adjust path if needed
          flags: unittests
          name: codecov-coverage
          fail_ci_if_error: true
